# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

1.14.0


#### 3. Create a null vector of size 10 (★☆☆)

In [35]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [6]:
print(len(x))

10


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [34]:
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [33]:
y=np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [32]:
z=[]
for i in np.arange(len(y)-1,-1,-1):
    z.append(y[i])
print(z)

[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
w=np.arange(0,9)
w.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [25]:
list=[1,2,0,0,4,0]
indices=[]
for i in np.arange(len(list)):
    if(list[i]!=0):
        indices.append(i)
print(indices)

[0, 1, 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [31]:
ident= np.eye(3,3)
print(ident)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [29]:
from numpy.random import uniform
randommatrix = uniform(low=0.0,high=1.0,size=[3,3,3])
print(randommatrix)

[[[0.4327709  0.96638883 0.60118459]
  [0.08101943 0.16204192 0.09553373]
  [0.83852072 0.19851152 0.41593161]]

 [[0.18947019 0.22464406 0.49183073]
  [0.89075215 0.08401826 0.42561393]
  [0.90150479 0.93521722 0.32058279]]

 [[0.465467   0.94250229 0.73635299]
  [0.98347963 0.92059766 0.9788372 ]
  [0.78457156 0.44148042 0.53008142]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [39]:
from numpy.random import uniform
randmat2 = uniform(low=3.0,high=5.0,size=[10,10])
print(randmat2[:].min())
print(randmat2[:].max())

3.000593621179714
4.993116212992025


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [42]:
from numpy.random import normal
randmat3 = normal(5.0,10.0,[30])
print(randmat3.mean())

6.566909156406882


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [82]:
borderarr=np.zeros([4,6])
borderarr[0,:]=1
borderarr[3,:]=1
borderarr[:,5]=1
borderarr[:,0]=1
print(borderarr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [91]:
oldshape=borderarr.shape
#lets do this the C++ way
newarr=np.zeros([oldshape[0]+2,oldshape[1]+2])
newarr[0,:]=np.zeros([1,oldshape[1]+2])
newarr[oldshape[0]+1,:]=np.zeros([1,oldshape[1]+2])
for i in np.arange(1,oldshape[0]+1):
    for j in np.arange(oldshape[1]+2):
        if(j==0) or (j==oldshape[1]+1):
            newarr[i,j]=0
        else:
            newarr[i,j]=borderarr[i-1,j-1]
print(newarr)
        

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [100]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [106]:
diagcount=np.diagflat([1,2,3,4])
np.insert(diagcount,0,0,axis=1)
np.insert(diagcount,0,0,axis=0)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [109]:
checkerboard=np.zeros([8,8])
checkerboard[::2,::2]=1
checkerboard[1::2,1::2]=1
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [129]:
100-7*8-5*8-4
print ([1,5,3])

[1, 5, 3]


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [7]:
import numpy as np
typea2=np.ones([2,2])
typeb2=np.zeros([2,2])
row1=np.concatenate((typea2,typeb2), axis=0)
row2=np.concatenate((typeb2,typea2),axis=0)
square=np.concatenate((row1,row2),axis=1)
bigsquare=np.tile(square,(2,2))
print(bigsquare)

[[1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 0. 0. 1. 1.]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [3]:
from numpy.random import uniform
rndtonorm=uniform(-5,-2,[5,5])
rndnorm=rndtonorm-rndtonorm.mean()
rangenorm=rndnorm.max()-rndnorm.min()
rndnorm=rndnorm/rangenorm
print(rndnorm)

[[-0.03996929 -0.18318606  0.53614163 -0.10516751  0.39277073]
 [ 0.38874742  0.33658036  0.50216681 -0.34739682 -0.40717004]
 [ 0.18422382 -0.29616751 -0.4403114  -0.3537931   0.15375511]
 [-0.34639231 -0.38759606 -0.4313855   0.03577716  0.1602744 ]
 [-0.32491197  0.5596886   0.38024103 -0.35088553  0.38396603]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [7]:
import numpy as np
matrix24a=uniform(0,1,[5,3])
matrix24b=uniform(0,1,[3,2])
np.matmul(matrix24a,matrix24b)

array([[0.94648675, 0.82135495],
       [0.37329883, 0.35312726],
       [1.29958582, 1.16451469],
       [0.94093473, 0.772226  ],
       [0.4437275 , 0.35526766]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [22]:
array25=np.arange(25)
for i in np.arange(len(array25)):
    if((array25[i]<=8) and (array25[i]>=3)):
        array25[i]*=-1
print(array25)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [25]:
9

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
1j*z, Z/1/1

NameError: name 'z' is not defined

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [41]:
temp=array25*.1
print(temp)
signarr=np.zeros(len(array25))
for i in np.arange(len(array25)):
        if array25[i]<0:
            signarr[i]=-1    
        elif array25[i]>0:
            signarr[i]=1
        else:
            signarr[i]=0
roundoutarr=signarr*np.ceil(signarr*temp)
print(roundoutarr)

[ 0.   0.1  0.2 -0.3 -0.4 -0.5 -0.6 -0.7 -0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4]
[ 0.  1.  1. -1. -1. -1. -1. -1. -1.  1.  1.  2.  2.  2.  2.  2.  2.  2.
  2.  2.  2.  3.  3.  3.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [43]:
np.intersect1d(roundoutarr,np.arange(5))

array([0., 1., 2., 3.])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
numpy.testing.suppress_warnings_dont

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [45]:
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [52]:
today=np.datetime64('today')
print(today-1,today,today+1)

2019-05-01 2019-05-02 2019-05-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [64]:
import datetime
for day in np.arange(1,31):
    print(datetime.date(2016,7,day))

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [82]:
A=[1.,2.,4.,7.]
B=[3.,5.,6.,9.]
print(A)
print(B)
for i in np.arange(len(A)):
    print(A[i]+B[i])
    print(-A[i]/2.)
    A[i]=(A[i]+B[i])**(-A[i]/2.)
print(A)


[1.0, 2.0, 4.0, 7.0]
[3.0, 5.0, 6.0, 9.0]
4.0
-0.5
7.0
-1.0
10.0
-2.0
16.0
-3.5
[0.5, 0.14285714285714285, 0.01, 6.103515625e-05]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [92]:
randomarr=np.random.uniform(0,100,10)
upper=np.ceil(randomarr)
print(upper)
lower=np.floor(randomarr)
print(lower)
truncated=np.trunc(randomarr)
print(truncated)
nearestinteger=np.rint(randomarr)
print(nearestinteger)
def randtrunc(somefloatarr):
    coinflip=np.random.binomial(1,0.5,len(somefloatarr))
    print(coinflip)
    for i in np.arange(len(somefloatarr)):
        if coinflip[i]==0:
            somefloatarr[i]=np.floor(somefloatarr[i])
        else:
            somefloatarr[i]=np.ceil(somefloatarr[i])
    return somefloatarr
randint=randtrunc(randomarr)
print(randint)

[100.  67.  31.  53.   8.  85.  87.  43.  68.   2.]
[99. 66. 30. 52.  7. 84. 86. 42. 67.  1.]
[99. 66. 30. 52.  7. 84. 86. 42. 67.  1.]
[99. 67. 31. 53.  8. 85. 87. 43. 67.  2.]
[0 0 1 0 0 0 0 1 1 0]
[99. 66. 31. 52.  7. 84. 86. 43. 68.  1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [96]:
row=np.arange(4)
matrix1=np.tile(row,(5,1))
print(matrix1)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [110]:
def square10():
    for i in np.arange(10):
        yield i*i
squareintsout=square10()
print(squareintsout)
for x in squareintsout:
    print(x)

<generator object square10 at 0x10c83bca8>
0
1
4
9
16
25
36
49
64
81


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [119]:
fencelength=11
fencerange=1.-0.
step=(fencerange/fencelength)
print(step)
vec10=np.arange(step,1.,step)
print(vec10)

0.09090909090909091
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [123]:
randvec=np.random.uniform(0,1,10)
randvec.sort()
print(randvec)

[0.05475568 0.05551326 0.06031712 0.08948381 0.27827878 0.41334354
 0.50599494 0.58543949 0.78877797 0.86243952]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [124]:
x=[1,2,3]
sum = 0
for item in x:
    sum +=item
print(sum)

6


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [128]:
A= np.random.uniform(0,1,50)
B=np.random.uniform(0,1,50)
def isequal(A,B):
    eq=True
    for i in np.arange(len(A)):
        if A[i]==B[i]:
            eq=eq and True
        else:
            eq=False
    return eq       
print(A)
print(B)
print(isequal(A,A))
print(isequal(A,B))        

[0.63815017 0.47601004 0.8013633  0.92327363 0.71090037 0.41865553
 0.3577873  0.52303499 0.49066762 0.4471917  0.22724655 0.73172536
 0.41267758 0.74372293 0.893092   0.27842394 0.47331989 0.63361236
 0.10311462 0.26415736 0.40381452 0.60746366 0.34537907 0.78940261
 0.37860661 0.07386983 0.03177978 0.4868637  0.3771923  0.68683646
 0.89573014 0.77974861 0.72806138 0.43370973 0.6578711  0.03252514
 0.37677369 0.8823973  0.96429412 0.98436507 0.00120754 0.58957204
 0.63528587 0.06866684 0.31516237 0.70034238 0.06695433 0.53261742
 0.02978606 0.51429206]
[0.12808838 0.66326961 0.94790487 0.55041818 0.77863041 0.32537898
 0.68632991 0.08222464 0.41259541 0.14720626 0.24878318 0.70587071
 0.05309627 0.78113223 0.27450561 0.94070581 0.061568   0.77901629
 0.23679752 0.98293397 0.13882332 0.74835894 0.09501539 0.98927705
 0.31649151 0.02323635 0.13860288 0.22133503 0.96158043 0.39875554
 0.05215503 0.39286682 0.11071877 0.98006386 0.41583305 0.74253024
 0.59194815 0.08211789 0.09129452 0.60

#### 43. Make an array immutable (read-only) (★★☆)

In [131]:
someimmutablearray=np.zeros(10)
someimmutablearray.flags.writeable=False
someimmutablearray[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [141]:
import math
print("rank 10, 2 tensor; 2 dimensional flat spacetime")
randtensor=np.random.uniform(0,10,(10,2))
print(randtensor)
polartensor=[]
for line in randtensor:
    x=line[0]
    y=line[1]
    radius=math.sqrt(x**2+y**2)
    phi=math.atan2(y,x)
    polarline=np.array([radius,phi])
    polartensor.append(polarline)
polartensor=np.array(polartensor)
print(polartensor)

rank 10, 2 tensor; 2 dimensional flat spacetime
[[0.89354156 1.07781643]
 [9.26986323 2.81518725]
 [7.87851428 1.77344418]
 [3.16062211 9.46796234]
 [7.48017018 3.7904535 ]
 [7.30864994 8.1486106 ]
 [9.74185039 2.09278867]
 [1.78252695 4.60975788]
 [2.25790358 6.12448917]
 [0.94042743 4.47021573]]
[[ 1.40003742  0.87860343]
 [ 9.68791224  0.29484089]
 [ 8.07564805  0.22140849]
 [ 9.98157517  1.24860528]
 [ 8.38573095  0.46901996]
 [10.9460595   0.83968562]
 [ 9.96410625  0.21160846]
 [ 4.94239517  1.20182032]
 [ 6.52744178  1.21758846]
 [ 4.5680666   1.36344376]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [145]:
randvec=np.random.uniform(0,1,10)
print(randvec)
maxnum=np.max(randvec)
for i in np.arange(len(randvec)):
    if randvec[i]==maxnum:
        randvec[i]=0
print(randvec)

[0.35869401 0.34597503 0.87035795 0.10087658 0.64208859 0.26946525
 0.26653948 0.22273365 0.02088395 0.73048202]
[0.35869401 0.34597503 0.         0.10087658 0.64208859 0.26946525
 0.26653948 0.22273365 0.02088395 0.73048202]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [160]:
fencepostlength=99
fencepostrange=1
step=fencepostrange/fencepostlength
coords=np.arange(0,1+step,step)
print(coords)
xy=np.array([coords,coords],dtype=[("x","f4"),("y","f4")])
print(xy)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [172]:
cij=[]
for xi in xy['x'][0]:
    cijline=[]
    for yi in xy['y'][0]:
        if (yi==xi):
            cijline.append(1000000000.)
        else:
            cijline.append(1./(xi-yi))
    cijline=np.array(cijline)
    cij.append(cijline)
cij=np.array(cij)
CIJstruct=np.array([cij], dtype=[("Cij","f4")])
print(cij)

[[ 1.00000000e+09 -9.90000001e+01 -4.95000000e+01 ... -1.02061858e+00
  -1.01020409e+00 -1.00000000e+00]
 [ 9.90000001e+01  1.00000000e+09 -9.90000001e+01 ... -1.03125003e+00
  -1.02061858e+00 -1.01020409e+00]
 [ 4.95000000e+01  9.90000001e+01  1.00000000e+09 ... -1.04210531e+00
  -1.03125003e+00 -1.02061858e+00]
 ...
 [ 1.02061858e+00  1.03125003e+00  1.04210531e+00 ...  1.00000000e+09
  -9.89998997e+01 -4.94999498e+01]
 [ 1.01020409e+00  1.02061858e+00  1.03125003e+00 ...  9.89998997e+01
   1.00000000e+09 -9.89998997e+01]
 [ 1.00000000e+00  1.01020409e+00  1.02061858e+00 ...  4.94999498e+01
   9.89998997e+01  1.00000000e+09]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [181]:
import sys
sys.float_info
sys.int_info
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

#### 49. How to print all the values of an array? (★★☆)

In [183]:
np.set_printoptions(threshold=np.nanny)

AttributeError: module 'numpy' has no attribute 'nanny'

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [185]:
myvec=np.random.uniform(0,50,10)
myscalar=36
closest=myvec[0]
for i in np.arange(len(myvec)):
    if np.abs(myvec[i]-myscalar)<np.abs(closest-myscalar):
        closest=myvec[i]
print(closest)
print(myvec)

33.23633647553492
[49.50901527 10.04102888 28.50755253 33.23633648 12.06175654 44.11625296
 29.56490997 32.32951887 18.00320046  4.97033276]


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:

rrand=np.random.uniform(0,1)
brand=np.random.uniform(0,1)
grand=np.random.uniform(0,1)
xyrbg=np.array([(1.,1., rrand,brand,grand)],dtype=[("x","f4"),("y","f4"),('r',"f4"),("b","f4"),("g","f4")])
for x in xyrbg:
    print(x)


(1., 1., 0.14539982, 0.06292658, 0.97182477)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [74]:
randcoord=np.random.uniform(-10,10,(100,2))
def distance(xy1,xy2):
    x1=xy1[0]
    y1=xy1[1]
    x2=xy2[0]
    y2=xy2[1]
    rsq=(x1-x2)**2+(y1-y2)**2
    return np.sqrt(rsq)
dij=np.zeros([randcoord.shape[0], randcoord.shape[0]])
i=0
j=0
for xy1 in randcoord:    
    j=0
    for xy2 in randcoord:
        dij[i,j]=distance(xy1,xy2)
        j+=1
    i+=1
print(dij)

[[ 0.         12.48782047  6.31216572 ... 12.15982181 14.73159184
   5.65695249]
 [12.48782047  0.          6.64132432 ...  6.49366726 24.00071353
   7.43934706]
 [ 6.31216572  6.64132432  0.         ...  9.03911492 19.94718814
   0.79841176]
 ...
 [12.15982181  6.49366726  9.03911492 ...  0.         19.58414066
   9.62991924]
 [14.73159184 24.00071353 19.94718814 ... 19.58414066  0.
  19.5788277 ]
 [ 5.65695249  7.43934706  0.79841176 ...  9.62991924 19.5788277
   0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [79]:
myfloat=1.
int(myfloat)

1

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [21]:
import numpy as np
f=open("FileToRead.txt","r")
flines=f.readlines()
farray=[]

for line in flines:
    linelist=line.replace("\n","").split(',')
    #intlinelist=map((lambda x: int(x)),linelist)
    intlinelist=np.ones(len(linelist))
    for i in np.arange(len(linelist)):
        ll=linelist[i].strip()
        if ll=='':
            intlinelist[i]=0
        else:
            intlinelist[i]=int(ll)
    farray.append(np.array(intlinelist))
print(np.array(farray))


[[ 1.  2.  3.  4.  5.]
 [ 6.  0.  0.  7.  8.]
 [ 0.  0.  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [24]:
mean=2.
std=4.
dimension=[3,6]
normrand=np.random.normal(mean,std,dimension)
print(normrand)

[[-8.90817567  1.72049729  1.58302377  4.26445675  0.41589201 -0.05773256]
 [ 0.82109143 -1.59877468 -0.35390387 -0.48374093  3.93121868  5.17708477]
 [ 0.58146242  3.72191282 -1.97973714  2.2276234   9.44508604  0.44447582]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [36]:
import numpy as np


def isprime(p,n):
    if p==2:
        return True
    elif p%n==0:
        return False
    elif n>p//2:
        return True
    else:
        return isprime(p,n+1) 
    
def isprimenum(p):
    return isprime(p,2)

print(isprimenum(2))
print(isprimenum(3))
print(isprimenum(4))
print(isprimenum(5))
print(isprimenum(6))
print(isprimenum(7))
print(isprimenum(8))
print(isprimenum(9))
print(isprimenum(11))
print(isprimenum(17))

def primesgen(p):
    primelist=[]
    for i in np.arange(2,p+1):
        if isprimenum(i):
            primelist.append(i)
    return primelist
primeslist=primesgen(100)
print(primeslist)

def factor(p,primeslist):
    factorlist=[]
    for item in primeslist:
        while p%item==0:
            p=p//item
            factorlist.append(item)
    return factorlist
print(factor(2,primeslist))
print(factor(3,primeslist))
print(factor(4,primeslist))
print(factor(6,primeslist))
print(factor(12,primeslist))
print(factor(24,primeslist))
print(factor(49,primeslist))
print(factor(56,primeslist))


    

True
True
False
True
False
True
False
False
True
True
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
[2]
[3]
[2, 2]
[2, 3]
[2, 2, 3]
[2, 2, 2, 3]
[7, 7]
[2, 2, 2, 7]


In [37]:
%%bash
git commit -m "facto routine written slightly better tested"

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
	modified:   100 Numpy exercises no solution.ipynb

no changes added to commit


#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)